#sep, end, and escape characters
print("This " + "is " + "Python!")
print("This","is","Python")
print("This","is","Python",sep ="***")
print("Hello",end="-")
print("World")
print("Hello \nWorld")
print("Hello \rWorld")
print ("This is the best\rPython")
print ("This is the best\r\nPython")
print("Hello \tWorld")
print("The Title is: \"Movie\"")